from __future__ import annotations

from pathlib import Path
import json

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AgingWire Research Intelligence</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#151515;background:#f5f4ef}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.hero{display:flex;gap:16px;align-items:end;justify-content:space-between;flex-wrap:wrap}.card{background:white;border:1px solid #ddd;border-radius:12px;padding:18px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.metric{font-size:1.8rem;font-weight:700}.meta{color:#666;font-size:.9rem}.score{font-size:1.25rem;font-weight:800}.tags{display:flex;gap:6px;flex-wrap:wrap}.tag{background:#eee;border-radius:999px;padding:4px 8px;font-size:.78rem}a{color:#154b7d}input,select{padding:10px;border:1px solid #bbb;border-radius:8px;background:white}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.item h3{margin-bottom:6px}.angles{margin-top:8px}details{margin-top:10px}.health-error{color:#8a1c1c}
</style></head><body><div class="wrap"><div class="hero"><div><h1>AgingWire research intelligence</h1><div class="meta" id="generated"></div></div></div><div class="grid" id="metrics"></div><div class="controls"><input id="q" placeholder="Search stories, sources, topics"><select id="topic"><option value="">All topics</option></select><select id="aud"><option value="">All opportunities</option><option value="undercovered">Undercovered</option><option value="localizable">Localizable</option></select></div><div id="items"></div><div class="card"><h2>Pipeline health</h2><div id="health"></div></div></div><script>
let DATA={};const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){let q=document.querySelector('#q').value.toLowerCase(),t=document.querySelector('#topic').value,a=document.querySelector('#aud').value;let rows=(DATA.evidence||[]).filter(x=>{let text=[x.title,x.source_id,...(x.topics||[])].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(t&&!(x.topics||[]).includes(t))return false;if(a==='undercovered'&&(x.b2b_coverage_count+x.b2c_coverage_count)>2)return false;if(a==='localizable'&&!x.localizable&&!(x.geographies||[]).length)return false;return true});document.querySelector('#items').innerHTML=rows.map(x=>`<article class="card item"><div class="score">${x.score??0}</div><h3><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)}</a></h3><div class="meta">${esc(x.source_id)} · B2B coverage ${x.b2b_coverage_count||0} · B2C coverage ${x.b2c_coverage_count||0}</div><div class="tags">${(x.topics||[]).map(z=>`<span class="tag">${esc(z)}</span>`).join('')}</div>${(x.story_angles||[]).length?`<div class="angles"><strong>Angles</strong><ul>${x.story_angles.map(z=>`<li>${esc(z)}</li>`).join('')}</ul></div>`:''}</article>`).join('')||'<div class="card">No matches.</div>'}
fetch('../outputs/latest.json').then(r=>r.json()).then(d=>{DATA=d;document.querySelector('#generated').textContent='Generated '+d.generated_at;document.querySelector('#metrics').innerHTML=`<div class="card"><div class="metric">${d.evidence_count||0}</div><div class="meta">evidence candidates</div></div><div class="card"><div class="metric">${d.coverage_count||0}</div><div class="meta">media coverage items</div></div><div class="card"><div class="metric">${(d.evidence||[]).filter(x=>(x.b2b_coverage_count+x.b2c_coverage_count)===0).length}</div><div class="meta">zero-coverage opportunities</div></div>`;let topics=[...new Set((d.evidence||[]).flatMap(x=>x.topics||[]))].sort();document.querySelector('#topic').innerHTML+=[...topics].map(x=>`<option>${esc(x)}</option>`).join('');let errors=[...(d.source_status||[]),...(d.media_status||[])].filter(x=>x.status==='error');document.querySelector('#health').innerHTML=errors.length?errors.map(x=>`<div class="health-error">${esc(x.source||x.publisher)}: ${esc(x.error)}</div>`).join(''):'All monitored collectors completed without reported errors.';render()}).catch(e=>document.querySelector('#items').innerHTML='<div class="card health-error">No pipeline output yet. Run the intelligence workflow first.</div>');['q','topic','aud'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));
</script></body></html>'''


def build_dashboard(path: str = "docs/index.html") -> Path:
    p = Path(path); p.parent.mkdir(parents=True, exist_ok=True); p.write_text(HTML, encoding="utf-8"); return p
